version: '3.4'

networks:
    dgm:
      name: dgm

services:

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      - "SA_PASSWORD=Admin@123"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
    networks:
      - dgm
    restart: on-failure

  authserver:
    image: ${DOCKER_REGISTRY-}authserver
    build:
      context: .
      dockerfile: AuthServer/Dockerfile
    ports:
        - '5050:80'
        - '5051:443'
    env_file:
      - prod.env
    environment:
        - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DGM_Identity_Db;User=sa;Password=Admin@123;MultipleActiveResultSets=true"
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=5051
        - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55word
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/AuthServer.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    depends_on:
        - sqlserver
    networks:
        - dgm
    restart: on-failure

  resourceapi:
    image: ${DOCKER_REGISTRY-}resourceapi
    build:
      context: .
      dockerfile: ResourceAPI/Dockerfile
    ports:
        - '6060:80'
        - '6061:443'
    environment:
      - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DGM_API;User=sa;Password=Admin@123;MultipleActiveResultSets=true"
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6061
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55word
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ResourceAPI.pfx
    volumes:
       - ~/.aspnet/https:/https:ro
    depends_on:
       - sqlserver
       - authserver
    networks:
       - dgm
    restart: on-failure

  #clientapp:
  #  image: ${DOCKER_REGISTRY-}clientapp
  #  build:
  #    context: ClientApp
  #    dockerfile: ClientApp/Dockerfile
  #  ports:
  #    - '4200:80'
  #  environment:
  #    - NODE_ENV=prod
  #  depends_on:
  #     - authserver
  #     - resourceapi
  #  networks:
  #     - dgm
  #  restart: on-failure