export interface UserKycModel{
    fullName: string,
    permanentAddress: string,
    temporaryAddress: string,
    contactNumber: string,
    alternativeContactNumber: string,
    citizenshipNumber: string,
    panNumber: number,
    gender: string,
    maritalStatus: string,
    fathersName: string,
    mothersName: string,
    spouseName: string,
    child1Name: string,
    child2Name: string,
    bloodGroup: string,
    anyMedication: boolean,
    anyMedicalCondition: boolean,
}